on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          allow-softlinks: true
          show-channel-urls: true
          use-only-tar-bz2: true

      - name: Install deps
        run : |
          conda install rdkit clangdev boost-cpp

      - name: Build the project
        run: | 
          export LIBCLANG_PATH=$CONDA_PREFIX/lib
          cargo build